export const indicators = [
  {
    id: 1,
    slug: "smc-order-blocks-pro",
    name: "SMC Order Blocks Pro",
    creator: "Alex Chen",
    creatorVerified: true,
    description:
      "Advanced Smart Money Concepts indicator that automatically detects institutional order blocks, breaker blocks, and mitigation zones.",
    price: 29,
    winRate: 72,
    rating: 4.8,
    reviewCount: 124,
    subscribers: 1247,
    category: "Price Action",
    sparkline: [10, 18, 14, 22, 19, 28, 25, 34, 30, 40, 37, 45],
    tags: ["Smart Money", "Order Blocks", "Alerts"],
    updatedDaysAgo: 3,
    totalTrades: 847,
    avgProfit: 2.8,
    maxDrawdown: -8.2,
    sharpeRatio: 2.14,
    profitFactor: 2.31,
  },
  {
    id: 2,
    slug: "volume-profile-deluxe",
    name: "Volume Profile Deluxe",
    creator: "TradeLab",
    creatorVerified: true,
    description:
      "Comprehensive volume profile tool with POC, VAH, VAL levels and dynamic volume nodes for any timeframe.",
    price: 19,
    winRate: 68,
    rating: 4.6,
    reviewCount: 89,
    subscribers: 890,
    category: "Volume",
    sparkline: [8, 12, 10, 18, 15, 22, 20, 26, 24, 30, 28, 35],
    tags: ["Volume", "Profile", "Levels"],
    updatedDaysAgo: 7,
    totalTrades: 623,
    avgProfit: 2.1,
    maxDrawdown: -10.5,
    sharpeRatio: 1.87,
    profitFactor: 1.95,
  },
  {
    id: 3,
    slug: "ai-trend-scanner-v3",
    name: "AI Trend Scanner v3",
    creator: "QuantEdge",
    creatorVerified: true,
    description:
      "ML-powered trend detection across multiple assets and timeframes simultaneously with predictive signals.",
    price: 49,
    winRate: 78,
    rating: 4.9,
    reviewCount: 203,
    subscribers: 2100,
    category: "AI/ML",
    sparkline: [10, 15, 20, 17, 25, 30, 27, 35, 40, 38, 50, 58],
    tags: ["AI", "ML", "Trend", "Multi-TF"],
    updatedDaysAgo: 1,
    totalTrades: 1204,
    avgProfit: 3.4,
    maxDrawdown: -6.8,
    sharpeRatio: 2.71,
    profitFactor: 3.12,
  },
  {
    id: 4,
    slug: "liquidity-sweep-detector",
    name: "Liquidity Sweep Detector",
    creator: "MarketOwl",
    creatorVerified: false,
    description:
      "Identify buy-side and sell-side liquidity sweeps in real-time. Perfect for fading institutional moves.",
    price: 15,
    winRate: 65,
    rating: 4.5,
    reviewCount: 67,
    subscribers: 640,
    category: "Price Action",
    sparkline: [5, 8, 12, 9, 15, 18, 14, 20, 18, 24, 22, 28],
    tags: ["Liquidity", "Sweeps", "Fading"],
    updatedDaysAgo: 14,
    totalTrades: 412,
    avgProfit: 1.8,
    maxDrawdown: -12.1,
    sharpeRatio: 1.54,
    profitFactor: 1.72,
  },
  {
    id: 5,
    slug: "multi-tf-momentum",
    name: "Multi-TF Momentum",
    creator: "SwingKing",
    creatorVerified: true,
    description:
      "Analyze momentum across 4 timeframes simultaneously. Get confluence signals for high-probability entries.",
    price: 24,
    winRate: 70,
    rating: 4.7,
    reviewCount: 112,
    subscribers: 1500,
    category: "Multi-Timeframe",
    sparkline: [8, 14, 11, 18, 22, 19, 26, 30, 28, 35, 32, 40],
    tags: ["Momentum", "Multi-TF", "Confluence"],
    updatedDaysAgo: 5,
    totalTrades: 739,
    avgProfit: 2.5,
    maxDrawdown: -9.3,
    sharpeRatio: 2.02,
    profitFactor: 2.18,
  },
  {
    id: 6,
    slug: "smart-money-concepts",
    name: "Smart Money Concepts",
    creator: "InstitutionalFX",
    creatorVerified: true,
    description:
      "All-in-one SMC toolkit: BOS, ChoCH, FVG, order blocks, premium/discount zones with bias indicator.",
    price: 39,
    winRate: 75,
    rating: 4.8,
    reviewCount: 178,
    subscribers: 1800,
    category: "Price Action",
    sparkline: [12, 18, 15, 24, 21, 30, 28, 36, 40, 38, 48, 55],
    tags: ["SMC", "FVG", "Order Blocks"],
    updatedDaysAgo: 2,
    totalTrades: 985,
    avgProfit: 3.1,
    maxDrawdown: -7.4,
    sharpeRatio: 2.45,
    profitFactor: 2.78,
  },
];

export const testimonials = [
  {
    id: 1,
    quote:
      "SMC Order Blocks Pro completely transformed my trading. The accuracy is insane — I've been consistently profitable for 6 months straight.",
    name: "Marcus R.",
    role: "Swing Trader",
    avatar: "M",
    rating: 5,
  },
  {
    id: 2,
    quote:
      "As a creator, IndicatorHub gives me the infrastructure I need. My indicators reached 500+ subscribers in 3 months. The platform handles everything.",
    name: "Sarah L.",
    role: "Indicator Creator",
    avatar: "S",
    rating: 5,
  },
  {
    id: 3,
    quote:
      "Finally a marketplace that actually verifies indicator performance. No more buying garbage scripts from sketchy sellers. Quality is night and day.",
    name: "James K.",
    role: "Day Trader",
    avatar: "J",
    rating: 5,
  },
];

export const faqs = [
  {
    q: "How do I access indicators after subscribing?",
    a: "After subscribing, you'll receive instant access through your TradingView account. Our system automatically adds the indicator to your TradingView library within minutes.",
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes, absolutely. You can cancel any subscription at any time from your dashboard. You'll retain access until the end of your current billing period.",
  },
  {
    q: "How are indicator stats calculated?",
    a: "All performance stats (win rate, profit factor, etc.) are backtested on verified historical data and updated regularly. Creators must submit their backtest methodology for review.",
  },
  {
    q: "What's the creator payout schedule?",
    a: "Creators on the free plan receive monthly payouts. Creator Pro subscribers get weekly payouts. Minimum payout threshold is $50.",
  },
  {
    q: "Do you verify indicator performance?",
    a: "Yes. All indicators go through a review process where our team verifies the backtesting methodology and live performance data before approval.",
  },
  {
    q: "Which TradingView plans are supported?",
    a: "IndicatorHub works with all TradingView plans including Basic, Essential, Plus, Premium, and Ultimate. Some indicators may require Premium or above for certain features.",
  },
];

export const reviews = [
  {
    id: 1,
    name: "Carlos M.",
    avatar: "C",
    date: "Jan 15, 2026",
    rating: 5,
    text: "Absolutely incredible indicator. The order block detection is accurate and the alerts work perfectly. My win rate went from 52% to 71% in two months.",
  },
  {
    id: 2,
    name: "Priya S.",
    avatar: "P",
    date: "Jan 8, 2026",
    rating: 5,
    text: "Best SMC indicator I've used. Very clean UI on the chart and the multi-timeframe feature is a game changer. Worth every penny.",
  },
  {
    id: 3,
    name: "Tom W.",
    avatar: "T",
    date: "Dec 22, 2025",
    rating: 4,
    text: "Great indicator, works exactly as advertised. The only thing I'd like is more customization options for the visuals. Still 4/5 easily.",
  },
];
